### ISSUE TITLE
OutOfMemoryError When invoking method plotVocab

### ISSUE THREAD

**Issue by hack1nt0** [SkymindIO/deeplearning4j-nlp-examples#1]
Excuse me, but I got a OutOfMemoryError when running the Visualization class, which is still exist after I reset the JVM options(-Xms15000m, -Xmx15000m). My stack trace is below:

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3380)
	at org.nd4j.linalg.api.buffer.DoubleBuffer.<init>(DoubleBuffer.java:32)
	at org.nd4j.linalg.api.buffer.DoubleBuffer.<init>(DoubleBuffer.java:27)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.createBuffer(BaseNDArrayFactory.java:160)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:332)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:324)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:133)
	at org.nd4j.linalg.jblas.NDArray.<init>(NDArray.java:82)
	at org.nd4j.linalg.jblas.JblasNDArrayFactory.create(JblasNDArrayFactory.java:177)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2547)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:1991)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.dup(BaseNDArray.java:982)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mul(BaseNDArray.java:2308)
	at org.deeplearning4j.plot.Tsne.gradient(Tsne.java:388)
	at org.deeplearning4j.plot.Tsne.step(Tsne.java:399)
	at org.deeplearning4j.plot.Tsne.calculate(Tsne.java:307)
	at org.deeplearning4j.plot.Tsne.plot(Tsne.java:418)
	at org.deeplearning4j.models.word2vec.wordstore.inmemory.InMemoryLookupCache.plotVocab(InMemoryLookupCache.java:659)
	at org.deeplearning4j.rottentomatoes.data.visualization.Visualization.main(Visualization.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

Looking forward to your replay.

**Comment by agibsonccc** [comment]
Use -Ddtype=float in your jvm arguments. You can also set this programatically widh Nd4j.dType = DataBuffer.FLOAT.

**Comment by hack1nt0** [comment]
Thank you for your replay. After Doing what you proposed, I avoid the outOfMemory. 

But I only receive some message like this: 

"o.d.plot.Tsne - Cost at interation <int> was <float>", 

without any pop-up graph windows. Wondering what is going wrong. Already installed the necessary python libraries as described in your website.
